
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\kaany\OneDrive\Desktop\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#D1D1D1")


canvas = Canvas(
    window,
    bg = "#D1D1D1",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    1.1368683772161603e-13,
    0.0,
    218.0000000000001,
    143.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    225.9999999999999,
    0.0,
    1440.0,
    143.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    0.0,
    218.0000000000001,
    143.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1426.0,
    143.0,
    1440.0,
    927.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    927.0,
    1440.0,
    1024.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    159.0,
    218.0000000000001,
    256.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    272.0,
    218.0000000000001,
    390.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    406.0,
    218.0000000000001,
    524.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    1.1368683772161603e-13,
    540.0,
    218.0000000000001,
    1065.0,
    fill="#00447B",
    outline="")

canvas.create_text(
    1.1368683772161603e-13,
    13.0,
    anchor="nw",
    text="EHL-I NISPET",
    fill="#FFFFFF",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    216.9999999999999,
    142.0,
    217.99999999999994,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    1198.0,
    295.0,
    1414.0,
    431.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1224.0,
    338.0,
    anchor="nw",
    text="Masa 3",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    1.1368683772161603e-13,
    927.0,
    1440.0,
    1024.0,
    fill="#00447B",
    outline="")

canvas.create_rectangle(
    741.9999999999999,
    295.0,
    957.9999999999999,
    431.0,
    fill="#F9F9F9",
    outline="")

canvas.create_rectangle(
    1108.0,
    159.0,
    1387.0,
    283.0,
    fill="#F8B7B7",
    outline="")

canvas.create_text(
    777.9999999999999,
    338.0,
    anchor="nw",
    text="Masa 1",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    969.9999999999999,
    295.0,
    1186.0,
    431.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1005.9999999999999,
    338.0,
    anchor="nw",
    text="Masa 2",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    740.9999999999999,
    453.0,
    956.9999999999999,
    589.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    740.9999999999999,
    496.0,
    anchor="nw",
    text="Masa 4",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    1140.0,
    194.0,
    anchor="nw",
    text="Günü bitir",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    969.9999999999999,
    453.0,
    1186.0,
    589.0,
    fill="#F9F9F9",
    outline="")

canvas.create_rectangle(
    969.9999999999999,
    453.0,
    1186.0,
    589.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1005.9999999999999,
    496.0,
    anchor="nw",
    text="Masa 5",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    969.9999999999999,
    611.0,
    1186.0,
    747.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    969.9999999999999,
    654.0,
    anchor="nw",
    text="Masa 8",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    1199.0,
    453.0,
    1415.0,
    589.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1235.0,
    496.0,
    anchor="nw",
    text="Masa 6",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    741.9999999999999,
    611.0,
    957.9999999999999,
    747.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    777.9999999999999,
    654.0,
    anchor="nw",
    text="Masa 7",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    969.9999999999999,
    769.0,
    1186.0,
    905.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    969.9999999999999,
    812.0,
    anchor="nw",
    text="Masa 11",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    1198.0,
    769.0,
    1414.0,
    905.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1217.0,
    812.0,
    anchor="nw",
    text="Masa 12",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    1198.0,
    611.0,
    1414.0,
    747.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    1234.0,
    654.0,
    anchor="nw",
    text="Masa 9",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    741.9999999999999,
    769.0,
    957.9999999999999,
    905.0,
    fill="#F9F9F9",
    outline="")

canvas.create_text(
    741.9999999999999,
    812.0,
    anchor="nw",
    text="Masa 10",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    13.999999999999886,
    168.0,
    anchor="nw",
    text="masalar",
    fill="#FFFFFF",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    23.999999999999886,
    426.0,
    anchor="nw",
    text="stok",
    fill="#FFFFFF",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    20.999999999999886,
    295.0,
    anchor="nw",
    text="menu",
    fill="#FFFFFF",
    font=("Itim Regular", 48 * -1)
)

canvas.create_rectangle(
    217.9999999999999,
    143.0,
    719.9999999999999,
    927.0,
    fill="#FBFBFB",
    outline="")

canvas.create_text(
    234.9999999999999,
    42.0,
    anchor="nw",
    text="Masa takip ve Adisyon Programı",
    fill="#FFFFFF",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    747.9999999999999,
    168.0,
    anchor="nw",
    text="Dolu Masalar: x ",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    747.9999999999999,
    227.0,
    anchor="nw",
    text="Boş Masalar: x ",
    fill="#000000",
    font=("Itim Regular", 48 * -1)
)

canvas.create_text(
    1097.0,
    953.0,
    anchor="nw",
    text="Günün bitmesine kalan süre: x saat x dk",
    fill="#FFFFFF",
    font=("Itim Regular", 32 * -1)
)

canvas.create_rectangle(
    216.9999999999999,
    142.0,
    217.99999999999994,
    927.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    718.9999999999999,
    144.0,
    719.9999999999999,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    216.9999999999999,
    811.0,
    720.0039978027343,
    812.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    216.9999999999999,
    746.0,
    720.0039978027343,
    747.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    467.9999999999999,
    746.0,
    469.0000000000029,
    812.0,
    fill="#000000",
    outline="")

canvas.create_text(
    217.9999999999999,
    756.0,
    anchor="nw",
    text="Toplam: x TL",
    fill="#000000",
    font=("Itim Regular", 32 * -1)
)

canvas.create_text(
    482.9999999999999,
    756.0,
    anchor="nw",
    text="Seçilenler: x TL",
    fill="#000000",
    font=("Itim Regular", 32 * -1)
)

canvas.create_rectangle(
    589.9999999999999,
    812.0,
    719.9999999999999,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    459.9999999999999,
    812.0,
    589.9999999999999,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    329.9999999999999,
    812.0,
    459.9999999999999,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    217.9999999999999,
    812.0,
    329.9999999999999,
    927.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    226.9999999999999,
    465.0,
    692.9999999999999,
    549.0,
    fill="#94D0FF",
    outline="")

canvas.create_text(
    240.9999999999999,
    487.0,
    anchor="nw",
    text="Bira",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_text(
    580.9999999999999,
    487.0,
    anchor="nw",
    text="10 Tl",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_rectangle(
    226.9999999999999,
    365.0,
    692.9999999999999,
    449.0,
    fill="#94D0FF",
    outline="")

canvas.create_text(
    240.9999999999999,
    387.0,
    anchor="nw",
    text="Bira",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_text(
    580.9999999999999,
    387.0,
    anchor="nw",
    text="10 Tl",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_rectangle(
    226.9999999999999,
    266.0,
    692.9999999999999,
    350.0,
    fill="#94D0FF",
    outline="")

canvas.create_text(
    240.9999999999999,
    288.0,
    anchor="nw",
    text="Bira",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_text(
    580.9999999999999,
    288.0,
    anchor="nw",
    text="10 Tl",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_rectangle(
    226.9999999999999,
    160.0,
    692.9999999999999,
    244.0,
    fill="#94D0FF",
    outline="")

canvas.create_text(
    240.9999999999999,
    182.0,
    anchor="nw",
    text="Bira",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_text(
    580.9999999999999,
    182.0,
    anchor="nw",
    text="10 Tl",
    fill="#000000",
    font=("Itim Regular", 36 * -1)
)

canvas.create_rectangle(
    701.9999999999999,
    145.0,
    717.9999999999999,
    741.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    702.9999999999999,
    240.0,
    717.9999999999999,
    283.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
